defaults:
  - _self_

trainer:
  seed: 42
  device: auto
  amp: true
  max_steps: 10000
  log_every: 1
  save_every: 1000
  save_dir: "saved"
  resume_from: null
  override: true

dataloader:
  batch_size: 8
  num_workers: 4

datasets:
  train:
    _target_: src.datasets.ruslan_dataset.RuslanWavDataset
    data_dir: data/ruslan
    segment_size: 8192
    target_sr: 22050
    mono: true
    normalize: true
    random_crop: true
    seed: ${trainer.seed}

batch_transforms: null

mel_transform:
  _target_: src.transforms.hifigan_mel.HiFiGANMel
  sr: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  fmin: 0.0
  fmax: 8000.0
  center: false
  pad_mode: reflect

model:
  _target_: src.model.baseline_model.HiFiGAN
  generator: {}
  msd: {}
  mpd: {}

loss_function:
  _target_: src.loss.hifigan_loss.HiFiGANLoss
  lambda_mel: 45.0
  lambda_fm: 2.0


metrics: {}

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0002
  betas: [0.8, 0.99]

optimizer_d:
  _target_: torch.optim.Adam
  lr: 0.0002
  betas: [0.8, 0.99]


lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

lr_scheduler_d:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

writer:
  _target_: src.logger.cometml.CometMLWriter

  project_name: "hifigan"
  workspace: "cnopkaf16"
  run_name: "hifigan_ruslan"

  experiment_name: "hifigan_ruslan"

  api_key: ${oc.env:COMET_API_KEY}

  log_code: false
  log_graph: false
  log_env_details: false
  id_length: 32
  experiment_key: null
  resume_id: null
  enable: true

